### ISSUE TITLE
Unconfigurable "/srv/users"?

### ISSUE THREAD

**Issue by yarikoptic** [debops/ansible-users#4]
Why would I need /srv/users on my system happen I decide to use quite quite lovely playbook? ;) and it seems to be used  nowhere

```
$> git grep srv/users
tasks/forward.yml:  template: src=srv/users/forward.j2 owner={{ item.name }} group={{ item.group | default(item.name) }} mode=0644
tasks/main.yml:  file: path=/srv/users state=directory owner=root group=root mode=0751
```

**Comment by drybjed** [comment]
Task which creates `/srv/users` has been removed from the role in https://github.com/debops/ansible-users/commit/ce759543eae32cbec98de433582113f2c5a38433
