### ISSUE TITLE
UnboundLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by christiancruz11** [debops/ansible-users#49]
Im trying to use the user management with creating a user and encountered this problem.
Appreciate any help.

ERROR! Unexpected Exception: local variable 'f' referenced before assignment
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 141, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 237, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 268, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 354, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 330, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, facts)
  File "/usr/lib/python2.7/site-packages/ansible/vars/__init__.py", line 578, in set_host_facts
    self._fact_cache[host.name] = facts
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 49, in __setitem__
    self._plugin.set(key, value)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/jsonfile.py", line 101, in set
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment

**Comment by drybjed** [comment]
It looks like you used a string somewhere where role expected a list, but I'm not sure. Can you show the configuration you used with this role? The above error message does not suggest anything we could work with...

**Comment by christiancruz11** [comment]
Hi,
Here is my playbook that calls the role:
cat playbooks/user_management.yml
---
- name: User management
  hosts: all
  become: yes

  pre_tasks:
    - include:
      vars:
        user_users:
          #- { name: sup-520553, state: absent, remove: yes }
          - { name: sup-520553, state: present }

  roles:
    - { role: user }

---------------------------------------------------------------
Ansible config file:
$ cat ansible.cfg
[defaults]
vault_password_file = /etc/ansible/ngito-vault-key
hostfile = ./inventory/vagrant
library = ./library
roles_path = roles:roles/galaxy
module_name = command
log_path = ./ansible.log
remote_tmp = $HOME/.ansible/tmp
pattern = *
forks=5
timeout=10
poll_interval=15
sudo_user=root
ask_sudo_pass=False
transport=ssh
remote_port=22
sudo_exe=sudo
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = ./plugins/action_plugins
callback_plugins   = ./plugins/callback_plugins
connection_plugins = ./plugins/connection_plugins
lookup_plugins     = ./plugins/lookup_plugins
vars_plugins       = ./plugins/vars_plugins
filter_plugins     = ./plugins/filter_plugins
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible_facts
fact_caching_timeout = 86400

[ssh_connection]
ssh_args=-o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3


--------
Output when I ran the command:
$ ansible-playbook playbooks/user_management.yml -i inventory/inventory --check -vvvv
Using /home/christiana/chorus-BAU/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: user_management.yml **************************************************
1 plays in playbooks/user_management.yml

PLAY [User management] *********************************************************

TASK [setup] *******************************************************************
<172.17.203.21> ESTABLISH SSH CONNECTION FOR USER: None
<172.17.203.21> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 172.17.203.21 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467879669.41-102940923151046 `" && echo ansible-tmp-1467879669.41-102940923151046="` echo $HOME/.ansible/tmp/ansible-tmp-1467879669.41-102940923151046 `" ) && sleep 0'"'"''
<172.17.203.21> PUT /tmp/tmpEinqyF TO /home/christiana/.ansible/tmp/ansible-tmp-1467879669.41-102940923151046/setup
<172.17.203.21> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 '[172.17.203.21]'
<172.17.203.21> ESTABLISH SSH CONNECTION FOR USER: None
<172.17.203.21> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -tt 172.17.203.21 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-efmpnafagkcuafjqxtsabzbjuainjdjs; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/christiana/.ansible/tmp/ansible-tmp-1467879669.41-102940923151046/setup; rm -rf "/home/christiana/.ansible/tmp/ansible-tmp-1467879669.41-102940923151046/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
 [WARNING]: error while trying to write to /tmp/ansible_facts/jmt01 : [Errno 13] Permission denied: u'/tmp/ansible_facts/jmt01'

ERROR! Unexpected Exception: local variable 'f' referenced before assignment
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 256, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 268, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 409, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 382, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, facts.copy())
  File "/usr/lib/python2.7/site-packages/ansible/vars/__init__.py", line 602, in set_host_facts
    self._fact_cache[host.name] = facts
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 49, in __setitem__
    self._plugin.set(key, value)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/jsonfile.py", line 104, in set
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
$

**Comment by drybjed** [comment]
This immidiately jumps out:
```
[WARNING]: error while trying to write to /tmp/ansible_facts/jmt01 : [Errno 13] Permission denied: u'/tmp/ansible_facts/jmt01'
```
Kind of weird... Are you sure that you can connect to the remote host and use `sudo` on it to switch to `root`? What Ansible version do you use? Can you test on `stable-2.0` branch?

**Comment by christiancruz11** [comment]
Thanks, its fixed now. I fixed the permission on /tmp/ansible_facts/ on the ansible server. Was trying to do that on the client earlier. Thanks for pointing that mistake.

**Comment by drybjed** [comment]
Good to know. In that case I'm closing this issue.
