### ISSUE TITLE
users_default checks only for ansible_ssh_user

### ISSUE THREAD

**Issue by scibi** [debops/ansible-users#51]
In Ansible 2.0 `ansible_ssh_user` is deprecated and replaced by `ansible_user`. So it should check for both `ansible_ssh_user` and `ansible_user`.

**Comment by drybjed** [comment]
This should be added to the `debops.core` role, and `debops.users` should switch to use the admin account names from `ansible_local.core.admin_users` lists. I'll look into that soon.

**Comment by drybjed** [comment]
This issue will be resolved by https://github.com/debops/ansible-users/pull/53/commits/bec3bcb3aa7128113df079510e3b734c1b98eaea

**Comment by drybjed** [comment]
This issue has been resolved in the `v0.2.0` version.
