### ISSUE TITLE
How to exclude a particular user?

### ISSUE THREAD

**Issue by aks** [debops/ansible-users#6]
I have a list of users in `group_vars/all/users_list.yml`, and I want to have `debops.ansible-users` manage those users -- except for one, on a particular system.

What's the best way to do that?  

Create two separate lists?

I was considering modifying the `debops.ansible-users` role to have variable called `exclude_users` variable that could be used on the command line, or in the inventory to temporarily exclude a particular user.

Also, it seems that the `debops.ansible-users` role is trying to manage the `root` user, even though it is not part of my inventory list.  

Partial output from a run:
```
TASK: [debops.users | Manage user accounts without UIDs] **********************
failed: [web-101] => (item={'name': u'root'}) => {"failed": true, "item": {"name": "root"}, "name": "root", "rc": 8}
msg: usermod: user root is currently used by process 1
```

Any insight into this problem?

Thanks

**Comment by aks** [comment]
Hmm.  In regard to the `root` user part of my question above, it seems that the role has a `defaults/main.yml` which defines `users_root`.  Perhaps this `users_root` variable is being added to the list of users to be managed, even though I don't want to actually manage the root user.

Perhaps this isn't a good default, or perhaps adding it to the user of users to manage needs to be reconsidered?

**Comment by aks** [comment]
So, I worked around the `root` user problem by setting `users_root:` to nothing in the task that invokes `debops.users`.

**Comment by drybjed** [comment]
The quickiest way to solve the exclusion problem would be to create a separate list in `host_vars/host/users.yml` named the same as in `group_vars/all/` but without that one user. Ansible will override the global list on that particular host.

As for blacklist... Yeah, it could be done. Just add a check if `item.name not in users_blacklist`. I can add itsay, tommorow? It's 1 AM here right now. ;-)

`root` account is managed in `users_root` list separately from other users and its use is meant in case that you want to install your own dotfiles or change the shell on `root` account.

The issue you have might indicate that you are running debops by connecting directly to `root` via ssh. This role is designed to manage admin accounts automatically (look for `users_admins` list). If you connect directly to `root`, this account is suddenly in `users_admins` list where it shouldn't be and cannot be protected there from accidental group changes, etc. You should use your own admin account instead.

**Comment by aks** [comment]
No need for the exclusion update.  I can do that with the `host_vars` override, as you suggested.

These ansible scripts are being used to instantiate a new host, and my "own" admin account doesn't exist yet -- only root.  So, the default behavior ought to be to install all _other_ accounts, except root.

But, I'm able to easily get the role to do the Right Thing for our usage.  

Thanks for this nice role, and for the prompt response.

**Comment by drybjed** [comment]
I suppose moving `users_root` to completely separate tasks and checking if `item.name != 'root'` should help the issues. I'll look into that tommorow.
